name: Deploy Eleventy Site

on:
  push:
    branches:
      - main  # Runs every time you push to main, like every time...
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # This clears the deprecation warning

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install

      - name: Create Build Directory
        run: mkdir -p _site && chmod 755 _site

      - name: Build Project
        run: npm run build:11ty # Ensures your 'dist' or '_site' folder is created

      - name: Sync Subdirectory to Host
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site/  # The subdirectory you want to move
          server-dir: ./domains/danow.ski/public_html/vipers-2026/ # The destination folder
          protocol: ftp
          port: 21
          log-level: verbose